[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "NSrWXNF3E4MDUVqD6hTSpAfcn6xW_zJptPxUM2D10H0"

[auth.google]
client_id = "1234-abc.apps.googleusercontent.com"
client_secret = "google-secret-xyz"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
